name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set version env
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          
      - name: Set name env
        run: echo "RELEASE_NAME=Cinematic-Cameras-V2_$RELEASE_VERSION" >> $GITHUB_ENV

      - name: "Build Packs"
        uses: Bedrock-OSS/regolith-action@v1.0.3
        with:
          profile: build

      - name: Zip MCAddon
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          directory: "./build"
          filename: $RELEASE_NAME.mcaddon

      - name: Zip Archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          directory: "./build"
          filename: $RELEASE_NAME.zip

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.RELEASE_NAME }}.mcaddon,${{ env.RELEASE_NAME }}.zip
          generateReleaseNotes: true
          makeLatest: true
          body: ${{ github.event.head_commit.message }}
